### ISSUE TITLE
Documentation should point to source code

### ISSUE THREAD

**Issue by edgarcosta** [oscar-system/Oscar.jl#1463] opened 2022-07-17 21:23 UTC
It would be great if the documentation could point to the source code of the methods mentioned.
This would be particular useful for methods with optional parameters that are ambiguous.

For example, flags like `check`, is unclear many times what checks are being done. A clear case of this is `GF` and `FiniteField`.
Obviously, one alternative is to write better documentation, but given that this is a open source project, it would be easier to quickly jump to the code, than trying to navigate the repo to figure out where the method is defined, in particular, in what subpackage.

**Comment by fingolfin** [comment] 2022-07-17 21:34
That's really difficult due to how limited Documenter is in when it comes to merging documentation from different sources (read: it has zero support for that, we have to hack it together). Furthermore AFAIK it can only insert links to methods with an attached docstring. But there can be many methods implementing one function.

I would instead recommend to use macros like `@which`, `@less`, `@edit` from the REPL

**Comment by edgarcosta** [comment] 2022-07-17 21:53
Thank you.

Feel free to close the issue if you find it unreasonable.

**Comment by fingolfin** [comment] 2023-03-15 14:31
This issue is quite reasonably, but I am closing it now as it is a duplicate of #588 (i.e., we are still tracking it via that issue)

**Closed as not planned by fingolfin** 2023-03-15 14:31 UTC
Labels: enhancement
