### ISSUE TITLE
hilbert_series is buggy in extreme cases

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Oscar.jl#1663] opened 2022-10-31 16:26 UTC
@wolfram, @hannes14, The `HilbertData` object when pushed to its limits behaves
in unpredictable ways. The problem point is the call to `Singular.hilbert_series`
where the answer returned from Singular is simply wrong.

First the code that fails

```
for n in (1, 2, 3, 4, 5, 6, 100, 200, 400, 800, 1023, 1024, 1025, 2000, 5000, 10920, 10921, 10922, 10923)
println()
@show n
  A, _ = quo(R, ideal(R, [w^n, x^n, y^n, z^n, u^n, v^n]))
  H = HilbertData(A.I)
@show (length(H.data)-2)/n
@show maximum(map(abs,H.data))
@show count(!=(0),H.data)
  @assert degree(A) == ZZ(n)^6
end
```

up to n <= 10922 we have the correct answers.
```
...

n = 10921
(length(H.data) - 2) / n = 6.0
maximum(map(abs, H.data)) = 20
count((!=)(0), H.data) = 7

n = 10922
(length(H.data) - 2) / n = 6.0
maximum(map(abs, H.data)) = 20
count((!=)(0), H.data) = 7
```
However, at n = 10923, we have anomalous `H.data` and a wrong answer and a crash.
```
n = 10923
(length(H.data) - 2) / n = 0.00027464982147761604
maximum(map(abs, H.data)) = 1
count((!=)(0), H.data) = 2
ERROR: LoadError: AssertionError: degree(A) == ZZ(n) ^ 6
Stacktrace:
 [1] top-level scope
   @ ~/otest.jl:13
 [2] include(fname::
signal (11): Segmentation fault
in expression starting at none:0
_Z8nlDeletePP7snumberP9n_Procs_s at /home/schultz/.julia/artifacts/4a8d11e912d38a57f1eea66b2622e66a11b78173/lib/libpolys.so (unknown line)
Allocations: 55698731 (Pool: 55652796; Big: 45935); GC: 32
Segmentation fault (core dumped)
```

-------------------------
It is well known that many of our polynomial implementations have limited degrees:
 - AbstractAlgebra: each degree < 2^63 (lex), total degree < 2^63 (deglex, degrevlex)
 - Singular: unknown exactly, but the degree bound can be configured, and bounds of 2^12, 2^20, 2^32 appear below

Q: Is this a degree bound issue?

A: I don't think so, but could be wrong. It seems we are getting 20 bit
exponents in the default case, and 32 bit exponents don't move the failure point
at all. Of course the failure point can be lowered by moving to 12 bit exponents,
but considering that the failure point is n = 2^10 in this case, this is not
completely unexpected.

```
option to Singular.PolyRing | first failed n | degree_bound stored in the Singular Ring
degree_bound = 2^7+1              1024         0x00000000000003ff
degree_bound = 0 (default)       10923         0x00000000000fffff
degree_bound = 2^31+1            10923         0x00000000ffffffff
degree_bound = 2^60+1            10923         0x00000000ffffffff
```

In every case, Singular randomly crashes at some point after the assertion fails.

**Comment by fingolfin** [comment] 2022-10-31 16:31
Orthogonal to this: could we perhaps switch to the new Hilbert series code by @HechtiDerLachs ?

**Comment by tthsqe12** [comment] 2022-10-31 16:39
This is also an interesting observation:
```
10922*6 < 2^16 < 10923*6
```

**Comment by HechtiDerLachs** [comment] 2022-11-01 11:13
> Orthogonal to this: could we perhaps switch to the new Hilbert series code by @HechtiDerLachs ?

In principle, we probably could, but I think this was not intended. @wdecker wanted the new code as a basis for the multi-hilbert series, but keep the classical singular implementation for the default case.

**Comment by fingolfin** [comment] 2022-11-01 20:04
@HechtiDerLachs well, I'd understand keep using the old code if it is "better" (e.g. faster), but as it is, in many examples the new code is faster; and actually giving a correct example is also nice to have?

**Comment by wdecker** [comment] 2022-11-01 22:18
@fingolfin There is a whole picture to be seen here. Let us discuss this next week after my holiday.
@tthsqe12 Thanks for catching this.

**Comment by tthsqe12** [comment] 2022-11-02 10:32
@hannes14 This worked in the Singular kernel as of January of this year. Now, in the function `hFirstSeries0` https://github.com/Singular/Singular/blob/eedce96bd7cce4843c40e5ad4ebd4b53d7fea7fb/kernel/combinatorics/hilb.cc#L1997-L2000
we have
```
    ss=new intvec(p_Totaldegree(s,Qt)+2);
    while(s!=NULL)
    {
      int i=p_Totaldegree(s,Qt);
```
Interestingly enough `p_Totaldegree` is supposed to return a `long int`, but, when the total degree is `10923*6`, something overflows, and `ss` ends up with a very insufficient length of `5`.

**Comment by hannes14** [comment] 2022-11-02 10:40
Fixed with https://github.com/Singular/Singular/commit/6494278d27d1617e138006df909851e815ccfe02
Was an overflow of exponenets of a poly in Qt

**Comment by tthsqe12** [comment] 2022-11-02 10:59
Can confirm this fixes it. So, this issue is resolved from my point of view.

**Comment by tthsqe12** [comment] 2022-11-02 12:59
@hannes14 One more thing, The Singular.jl tests
```
   R1, = PolynomialRing(QQ, ["x", ])
   @test degree_bound(R1) == 65535

   R2, = PolynomialRing(QQ, ["x", "y"]; degree_bound = 3)
   @test degree_bound(R2) == 65535
```
now fail as the lhs is 2^32-1. Is there any reason one would want the exact degree bound in the tests, or can I just delete these tests?

**Comment by hannes14** [comment] 2022-11-02 13:05
PolynomialRing(QQ, ["x", "y"]; degree_bound = n)
should result in 
degree_bound(R2) >= n

**Comment by fingolfin** [comment] 2023-03-15 15:03
I wanted to reproduce the initial example, but the definition of `R` is missing. I tried this, and the example did not crash:
```julia
R, (u,v,w,x,y,z) = graded_polynomial_ring(QQ, ["u","v","w","x","y","z"]
```
Also @tthsqe12 said it is fixed. So I am closing this.

**Closed as completed by fingolfin** 2023-03-15 15:03 UTC
Labels: bug
