### ISSUE TITLE
Oscar silently changes orderings of ideal gens

### ISSUE THREAD

**Issue by YueRen** [oscar-system/Oscar.jl#1914] opened 2023-02-09 14:17 UTC
Edit: @thofma: There is something strange going on for the ideal generator things, since Oscar silently changes the orderings of `IdealGen` objects:

```julia
julia> R, (x, y) = polynomial_ring(QQ, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Rational Field, fmpq_mpoly[x, y])

julia> I = ideal(R, x*y);

julia> G = groebner_basis(I);

julia> G.ord
degrevlex([x, y])

julia> II = ideal(G);

julia> groebner_basis(II, ordering = degrevlex([y, x]));

julia> G.ord
degrevlex([y, x])
```

<details><summary>Original example from @YueRen </summary>
<p>

In the example below, the final `groebner_basis(I,ordering=degrevlex(R))` returns the correct Groebner basis with respect to `degrevlex(R)` (see also `G`), but it claims that the Groebner basis is with respect to `adjacentOrdering` which it is not (see also `Gprime`)

```
using Oscar
R,(p01,p02,p03,p04,p12,p13,p14,p23,p24,p34) = PolynomialRing(QQ,["p01","p02","p03","p04","p12","p13","p14","p23","p24","p34"])

I = ideal(R,[p23*p14-p13*p24+p12*p34,
             p23*p04-p03*p24+p02*p34,
             p13*p04-p03*p14+p01*p34,
             p12*p04-p02*p14+p01*p24,
             p12*p03-p02*p13+p01*p23])

G = groebner_basis(I)

u = Int[-1, -1, 0, 0, 0, 0, -1, 0, -2, -1]
v = Int[0, 0, 0, 0, 1, 0, -1, -1, 0, 1]
n = ngens(R)
adjacentOrdering = weight_ordering(ones(Int,n),
                                   weight_ordering(u,
                                                   weight_ordering(v,lex(R))))
Gprime = groebner_basis(ideal(G),ordering=adjacentOrdering,complete_reduction=true)

groebner_basis(I,ordering=degrevlex(R))
```

**System:**
```
ulia> Oscar.versioninfo(full=true)
OSCAR version 0.11.3-DEV - #yr/groebnerFan, e7373cf7e -- 2023-02-07 15:50:54 +0000
  combining:
    AbstractAlgebra.jl   v0.27.8
    GAP.jl               v0.9.2
    Hecke.jl             v0.17.2
    Nemo.jl              v0.32.7
    Polymake.jl          v0.8.3
    Singular.jl          v0.16.1
  building on:
    Antic_jll               v0.201.500+0
    Arb_jll                 v200.2300.0+0
    Calcium_jll             v0.401.100+0
    FLINT_jll               v200.900.4+0
    GAP_jll                 v400.1200.200+0
    Singular_jll            v403.101.500+0
    libpolymake_julia_jll   v0.8.3+1
    libsingular_julia_jll   v0.29.0+0
    polymake_jll            v400.700.1+1
See `]st -m` for a full list of dependencies.

Julia Version 1.8.5
Commit 17cfb8e65ea (2023-01-08 06:45 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores
Official https://julialang.org/ release
```
</p>

**Comment by thofma** [comment] 2023-02-10 07:55
I digged a little into it. The problematic method is here:

https://github.com/oscar-system/Oscar.jl/blob/169ccdf41f7ac1a55e828530253aa215b1a11534/src/Rings/mpoly.jl#L654-L662

It is clear that this cannot work and is broken by design. No function should ever modify `I.ord` if `I::IdealGens` is the input.

This is called in

https://github.com/oscar-system/Oscar.jl/blob/169ccdf41f7ac1a55e828530253aa215b1a11534/src/Rings/groebner.jl#L94

Not sure who should take of this, but @wdecker, @ederc or @jankoboehm will figure it out.

**Comment by YueRen** [comment] 2023-02-10 08:00
Is there a preferred way to modify `I.ord` for `I::IdealGens`? (Though in my cases it is about `IdealGens` that are created locally from a `Vector{MPolyElem}` which I know forms a Groebner basis.)

**Comment by ederc** [comment] 2023-02-10 09:01
The main problem (in the original example) is that your second GB call is done not on `I` but on `ideal(G)`, that leads to the following problem:
```
julia> ideal(G).gens === I.gb[degrevlex([p01, p02, p03, p04, p12, p13, p14, p23, p24, p34])]
true
```
Then, as @thofma pointed out, `singular_assure()` with `adjacent_ordering` is overriding the `.ord` entry of `I.gb[degrevlex([p01, p02, p03, p04, p12, p13, p14, p23, p24, p34])]`. That's really broken by design. Is the `.ord` entry used for anything besides printing?

**Comment by thofma** [comment] 2023-02-10 09:03
I thought the whole point of the `IdealGens` business was to work with Groebner basis/generating sets, including keeping track of their ordering.

**Comment by ederc** [comment] 2023-02-10 09:04
Don't ask me.

**Comment by YueRen** [comment] 2023-02-10 09:05
@ederc I was using the `.ord` to keep track of the different orderings during the Groebner walk. Or rather, I was planning to. Let me know if that is not a good idea.

**Comment by jankoboehm** [comment] 2023-02-10 12:34
This function signature should not exist at all.

The analogue for ModuleGens has only the signature 
singular_assure(F::ModuleGens) 
and similar for oscar_assure. 

The wrong signature was obviously kept from BiPolyArray where it should also not have existed in the first place.

So it looks that the following three things go wrong here:

1) The function signature should not exist.
2) The function calling it (groebner_basis or friends) should not call this signature in the first place (again probably kept from BiPolyArray).
3) The ideal generated from a Groebner basis should have this Groebner basis as its generating set, but this should never be touched when computing a Groebner basis further on (again probably kept from BiPolyArray).

We will look into the details, but it seems it just has to be done analogously as for ModuleGens.

**Comment by YueRen** [comment] 2023-02-10 15:25
In line with what @jankoboehm said, the change of `.ord` does not only occur when calling `groebner_basis`, but also functions like `reduce`:

```
R,(p01,p02,p03,p04,p12,p13,p14,p23,p24,p34) = PolynomialRing(QQ,["p01","p02","p03","p04","p12","p13","p14","p23","p24","p34"])
I = ideal(R,[p23*p14-p13*p24+p12*p34,
             p23*p04-p03*p24+p02*p34,
             p13*p04-p03*p14+p01*p34,
             p12*p04-p02*p14+p01*p24,
             p12*p03-p02*p13+p01*p23])

G = groebner_basis(I)
H = groebner_basis(ideal(collect(G)),ordering=lex(R)) # collect(...) is important
                                                      # no collect(...), no bug

@assert H.ord == lex(R) # works
_ = reduce(H,G,ordering=G.ord)
@assert H.ord == lex(R) # breaks!
```

**Comment by jankoboehm** [comment] 2023-02-10 17:24
Just a note: In many places which rely on the wrong signature taken over from BiPolyArray, the fix is just removing the ord argument, since the ordering is passed later to the computation. In other places to address (3), on has to construct an IdealGens with the desired ordering and pass that into the computation. Currently the assure function with the additional argument is used to abuse the generating set as input while modifying its ord field.

**Comment by fieker** [comment] 2023-02-24 14:32
Current dev:
```
julia> G = groebner_basis(I);
G.ord
ERROR: TypeError: in keyword argument ordering, expected Symbol, got a value of type Singular.sordering
Stacktrace:
 [1] kwcall(::NamedTuple{(:ordering, :cached), Tuple{Singular.sordering, Bool}}, ::typeof(polynomial_ring), R::Singular.Rationals, s::Vector{String})
   @ AbstractAlgebra ~/.julia/dev/AbstractAlgebra/src/MPoly.jl:1297
 [2] singular_poly_ring(Rx::QQMPolyRing, ord::MonomialOrdering{QQMPolyRing})
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly.jl:550
 [3] singular_assure(I::Oscar.IdealGens{QQMPolyRingElem}, ordering::MonomialOrdering{QQMPolyRing})
   @ Oscar ~/.julia/dev/Oscar/src/Rings/mpoly.jl:657
 [4] _compute_standard_basis(B::Oscar.IdealGens{QQMPolyRingElem}, ordering::MonomialOrdering{QQMPolyRing}, complete_reduction::Bool)
   @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:94
 [5] standard_basis(I::MPolyIdeal{QQMPolyRingElem}; ordering::MonomialOrdering{QQMPolyRing}, complete_reduction::Bool, algorithm::Symbol)
   @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:150
 [6] #groebner_basis#873
   @ ~/.julia/dev/Oscar/src/Rings/groebner.jl:284 [inlined]
 [7] groebner_basis(I::MPolyIdeal{QQMPolyRingElem})
   @ Oscar ~/.julia/dev/Oscar/src/Rings/groebner.jl:281
 [8] top-level scope

**Comment by micjoswig** [comment] 2023-02-24 14:34
I have the following use case, which is related: grassmann_pluecker_ideal comes with generators which already form a Groebner basis, but for a very special term order (that we could specify).  Ideally, the information about the Groebner basis should be made known to OSCAR (avoiding computing a Groebner basis if it is not necessary).

**Comment by jankoboehm** [comment] 2023-02-24 17:59
The issue should be fixed hopefully very soon. You can then define the monomial ordering (provided you can write it down in OSCAR, which should be possible), make an IdealGens from your generators and the ordering, set isGB and, if appropriate, isReduced, and then add it to the gb Dict of your ideal. If you then ask to compute a Gröbner basis wrt the specific ordering, you will automatically get the result from the Dict. 

If you want to use your basis, you still have to be careful. Ideally, if you ask for a computation internally using a Gröbner basis and no other basis is known, your basis should be used. Currently, the default ordering of the base ring might be used, but you can specify your ordering, e.g. to ideal_membership (though not e.g. to is_subset and more elaborate stuff). That behavior should probably be changed, since if there is already a basis known, that is most likely wrt a more cleverly chosen ordering than that associated to the ring. 

The SubModuleOfFreeModule has a field where one can specify a default ordering for that specific module to exaclty accomodate the situation that for a given module there is a cleverly chosen ordering known. If something invokes a Gröbner basis computation far down, where one does not have access to, that ordering is used. Probably the same should be implemented for ideals.

**Comment by YueRen** [comment] 2023-03-03 14:52
Just a quick bump. Is there already a concrete timeline for when this issue will be resolved? @jankoboehm claims that the fix is straightforward. If not, I can work around the problem, which is probably equally straightforward but involves changing large parts of my code (because I will have to manually track something which I'm currently relying on OSCAR for).

**Comment by jankoboehm** [comment] 2023-03-03 16:04
You'll have it early next week.

**Comment by fingolfin** [comment] 2023-03-09 11:59
@jankoboehm any news?

**Comment by jankoboehm** [comment] 2023-03-09 14:42
singular_assure is used wrongly in about 16 places, so it takes a bit.. Will propose fix soon.

**Comment by thofma** [comment] 2023-12-22 15:49
Fixed on master.

**Closed as completed by thofma** 2023-12-22 15:49 UTC
Labels: bug, singular coding sprint
