### ISSUE TITLE
Factoring polynomials over finite fields does not work.

### ISSUE THREAD

**Issue by delphinepol** [oscar-system/Oscar.jl#188] opened 2020-11-19 12:46 UTC
I ran the the following example and Oscar crashed:
```
julia> K = GF(2)
Galois field with characteristic 2

julia> ZS, (a,b,c) = PolynomialRing(K, ["a", "b", "c"])
(Multivariate Polynomial Ring in a, b, c over Galois field with characteristic 2, AbstractAlgebra.Generic.MPoly{Nemo.gfp_elem}[1*a, 1*b, 1*c])

julia> F = a*b^4+b*c^4+a*c^4
1*a*b^4 + 1*a*c^4 + 1*b*c^4

julia> factor(F)
   ? multivariate factorization depends on NTL(missing)
   ? not implemented

signal (11): Segmentation fault
in expression starting at REPL[5]:1
length at /workspace/destdir/include/singular/misc/intvec.h:94 [inlined]
operator() at /workspace/srcdir/libsingular-julia-0.2.0/rings.cpp:269 [inlined]
_M_invoke at /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/7.1.0/bits/std_function.h:302
operator() at /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/7.1.0/bits/std_function.h:706 [inlined]
operator() at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/jlcxx/module.hpp:47 [inlined]
apply at /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include/jlcxx/module.hpp:72
singclap_factorize at /home/pol/.julia/packages/CxxWrap/ZOkSN/src/CxxWrap.jl:590 [inlined]
factor at /home/pol/.julia/packages/Singular/cuKCT/src/poly/poly.jl:734
factor at /home/pol/.julia/dev/Oscar/src/Rings/mpoly.jl:1105
jl_apply at /home/pol/julia/src/julia.h:1690 [inlined]
do_call at /home/pol/julia/src/interpreter.c:117
eval_value at /home/pol/julia/src/interpreter.c:206
eval_stmt_value at /home/pol/julia/src/interpreter.c:157 [inlined]
eval_body at /home/pol/julia/src/interpreter.c:548
jl_interpret_toplevel_thunk at /home/pol/julia/src/interpreter.c:660
jl_toplevel_eval_flex at /home/pol/julia/src/toplevel.c:840
jl_toplevel_eval_flex at /home/pol/julia/src/toplevel.c:790
jl_toplevel_eval_in at /home/pol/julia/src/toplevel.c:883
eval at ./boot.jl:331
eval_user_input at /home/pol/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
repl_backend_loop at /home/pol/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
start_repl_backend at /home/pol/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
#run_repl#37 at /home/pol/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
run_repl at /home/pol/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
#806 at ./client.jl:399
jfptr_YY.806_37718 at /home/pol/julia/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/pol/julia/src/julia.h:1690 [inlined]
do_apply at /home/pol/julia/src/builtins.c:655
jl_f__apply_latest at /home/pol/julia/src/builtins.c:705
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
run_main_repl at ./client.jl:383
exec_options at ./client.jl:313
_start at ./client.jl:506
jfptr__start_30174 at /home/pol/julia/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/pol/julia/ui/../src/julia.h:1690 [inlined]
true_main at /home/pol/julia/ui/repl.c:106
main at /home/pol/julia/ui/repl.c:227
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
_start at /home/pol/julia/./julia (unknown line)
Allocations: 50547644 (Pool: 50508299; Big: 39345); GC: 25
Segmentation fault (core dumped)
```

**Comment by fingolfin** [comment] 2020-11-20 11:38
I can reproduce this. It is another case where we run into Singular code that is not yet working w/o FLINT. But it really shouldn't be crashing.

This is really a bug in Singular.jl resp. Singular;  

@hannes14 @tthsqe12 . Even when the factorization doesn't work, it shouldn't crash like this, can we do at least something about it? Perhaps this would already be better with the latest Singular `spielwiese`? In that case, we could update Singular_jll...

**Comment by hannes14** [comment] 2020-11-20 12:51
Factoring over algebraic extensions of Z/p does not work without NTL, even with the new Flint.
I chnaged libsingular, so that now (after printing an error message) a valid result is return:
f is factored into (f^1)

**Comment by tthsqe12** [comment] 2020-11-20 13:31
I am calling the state of flint mpoly factor after https://github.com/wbhart/flint2/pull/852 useable, and am working as fast as I can to get a few more issues sorted out for a release.

**Comment by fingolfin** [comment] 2020-11-20 14:07
@hannes14 is there a way we can instead get the function to return an error code indicating that factoring failed, and then we turn that into an exception on the Julia side?

**Comment by hannes14** [comment] 2020-11-20 14:47
There is a global flag in libSingular (error_reported) which is set in an error case.

**Comment by fingolfin** [comment] 2020-11-25 08:08
@hannes14 so whenever we made any call into libSingular, we then need to check `error_reported` ? This sounds like a major change to Singular.jl and/or libsingular_julia_jll is required, where we change every single call into Singular to check that status of `error_reported` -- that sounds like a major headache?

I also wonder: in which situations is it useful for factorize to return an incorrect but "plausible" result like that? I.e., it effectively ends up claiming that any polynomial is irreducible -- to me, that is almost worse than a crash; with a crash, at least I know something went wrong; with a wrong result, my algorithm might seemingly complete but produce garbage.

So my guess is that there are applications within Singular which would rather get an incomplete factorization than nothing? Is that so? What are they?

**Comment by hannes14** [comment] 2020-11-25 10:22
The factorizing Groebner algorthm needs for examaple such factorization.
In Singular this "fake" result is not used because the interpeter checks always error_repoted.

Error reporting in Singular works as follows: if an error occurs WerrorS is called: which sets error_reported
(checked an reset by the interpreter) and calls the function pointer WerrorS_callback with astring (the error message).
By default the message is simply printed).
So another (simpler) way of handling an error in libSingular would be
to set this function pointer to something producing a traceable error in julia.

**Comment by thofma** [comment] 2020-12-23 11:43
This is a problem in Nemo. We are missing some things.

**Comment by tthsqe12** [comment] 2021-03-12 10:18
can close this? This is what I get now in oscar (sorry about all of the flubs along the way, but it seems to be working):
```
$ julia-1.5.3/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> status
ERROR: UndefVarError: status not defined

(@v1.5) pkg> status
Status `~/.julia/environments/v1.5/Project.toml`
  [c3fe647b] AbstractAlgebra v0.13.6
  [1f15a43c] CxxWrap v0.11.2
  [e30172f5] Documenter v0.26.3
  [7073ff75] IJulia v1.23.2
  [f1435218] Oscar v0.5.1
  [bcd08a7b] Singular v0.4.6
  [43d676ae] Singular_jll v402.0.102+1

(@v1.5) pkg> up
   Updating registry at `~/.julia/registries/General`
######################################################################## 100,0%
No Changes to `~/.julia/environments/v1.5/Project.toml`
No Changes to `~/.julia/environments/v1.5/Manifest.toml`

(@v1.5) pkg> K = GF(2)
ERROR: Could not determine command

julia> K = GF(2)
ERROR: UndefVarError: GF not defined
Stacktrace:
 [1] top-level scope at REPL[5]:1

julia> using Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
[ Info: Generating module common
[ Info: Generating module ideal
[ Info: Generating module graph
[ Info: Generating module fulton
[ Info: Generating module fan
[ Info: Generating module group
[ Info: Generating module polytope
[ Info: Generating module topaz
[ Info: Generating module tropical
[ Info: Generating module matroid
[ Info: Set up gaproot at /home/schultz/.julia/packages/GAP/Gc53G/gaproot/v1.5
[ Info: selected gcc as C compiler
[ Info: selected g++ as C++ compiler
[ Info: Generating custom Julia project ...
Path `../..` exists and looks like the correct package. Using existing path.
  Resolving package versions...
Updating `~/.julia/packages/GAP/Gc53G/gaproot/v1.5/Project.toml`
  [c863536a] + GAP v0.5.2 `../..`
Updating `~/.julia/packages/GAP/Gc53G/gaproot/v1.5/Manifest.toml`
  [56f22d72] + Artifacts v1.3.0
  [c863536a] + GAP v0.5.2 `../..`
  [5cd7a574] + GAP_jll v400.1100.1+0
  [de1ad85e] + GAP_lib_jll v400.1100.0+0
  [781609d7] + GMP_jll v6.1.2+6
  [78b55507] + Gettext_jll v0.20.1+7
  [692b3bcd] + JLLWrappers v1.2.0
  [94ce4f54] + Libiconv_jll v1.16.0+7
  [68e3532b] + Ncurses_jll v6.1.0+5
  [05236dd9] + Readline_jll v8.0.4+1
  [02c8fc9c] + XML2_jll v2.9.10+3
  [83775a58] + Zlib_jll v1.2.11+18
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode
No Changes to `~/.julia/packages/GAP/Gc53G/gaproot/v1.5/Project.toml`
No Changes to `~/.julia/packages/GAP/Gc53G/gaproot/v1.5/Manifest.toml`
[ Info: Generating gap.sh ...
[ Info: Compiling JuliaInterface ...
 -----    -----    -----      -      -----   
|     |  |     |  |     |    | |    |     |  
|     |  |        |         |   |   |     |  
|     |   -----   |        |     |  |-----   
|     |        |  |        |-----|  |   |    
|     |  |     |  |     |  |     |  |    |   
 -----    -----    -----   -     -  -     -  

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.5.1 ... 
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2021 by The Oscar Development Team

julia> ZS, (a,b,c) = PolynomialRing(K, ["a", "b", "c"])
ERROR: UndefVarError: K not defined
Stacktrace:
 [1] top-level scope at REPL[7]:1

julia> K = GF(2)
Galois field with characteristic 2

julia> ZS, (a,b,c) = PolynomialRing(K, ["a", "b", "c"])
(Multivariate Polynomial Ring in a, b, c over Galois field with characteristic 2, gfp_mpoly[a, b, c])

julia> F = a*b^4+b*c^4+a*c^4
a*b^4 + a*c^4 + b*c^4

julia> factor(F)
1 * (a*b^4 + a*c^4 + b*c^4)

**Comment by delphinepol** [comment] 2021-03-12 10:46
@tthsqe12 You can close it, I tried it, it works, thank you !

**Comment by tthsqe12** [comment] 2021-03-12 11:04
I can't close it, I think you have to :)

**Closed as completed** 2021-03-12 11:12 UTC
Labels: package: Nemo
