### ISSUE TITLE
Difference in printing in REPL versus doctests

### ISSUE THREAD

**Issue by wdecker** [oscar-system/Oscar.jl#2335] opened 2023-05-03 07:56 UTC
There still occur huge differences between interactive printing and the printing created when running tests. This is not only cumbersome for developers when trying to get the tests green, it might also repell new users as printing during tests may be almost unreadable. Here are two particular examples from PR #2334. @fingolfin @fieker @thofma @jankoboehm 

The examples are in ModulesGraded.jl:

Active printing:
----------------
```
julia> R, x, y = polynomial_ring(QQ, "x" => 1:2, "y" => 1:3);

julia> S, (x, y, z) = graded_polynomial_ring(QQ, ["x", "y", "z"], [1 0 1; 0 1 1]);

julia> FF = graded_free_module(S, [[1, 2], [-1, 3]])
Graded free module S^1([-1 -2]) + S^1([1 -3]) of rank 2 over S
```
Test printing:
--------------
```
julia> S, (x, y, z) = graded_polynomial_ring(QQ, ["x", "y", "z"], [1 0 1; 0 1 1]);

julia> FF = graded_free_module(S, [[1, 2], [-1, 3]])
Graded free module Multivariate Polynomial Ring in x, y, z over Rational Field graded by
  x -> [1 0]
  y -> [0 1]
  z -> [1 1]^1([-1 -2]) + Multivariate Polynomial Ring in x, y, z over Rational Field graded by
  x -> [1 0]
  y -> [0 1]
  z -> [1 1]^1([1 -3]) of rank 2 over Multivariate Polynomial Ring in x, y, z over Rational Field graded by
  x -> [1 0]
  y -> [0 1]
  z -> [1 1]
```
Another awful test print-out:
------------------------------
```
julia> R, (x, y) = graded_polynomial_ring(QQ, ["x", "y"])
(Multivariate Polynomial Ring in x, y over Rational Field graded by 
  x -> [1]
  y -> [1], MPolyDecRingElem{QQFieldElem, QQMPolyRingElem}[x, y])

julia> S, _ = quo(R, [x*y])
(Quotient of Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] by ideal(x*y), Map from
Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] to Quotient of Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] by ideal(x*y) defined by a julia-function with inverse)

julia> F = free_module(S, 2)
Free module of rank 2 over Quotient of Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] by ideal(x*y)

julia> FF = grade(F, [1, 2])
Graded free module Quotient of Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] by ideal(x*y)^1([-1]) + Quotient of Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] by ideal(x*y)^1([-2]) of rank 2 over Quotient of Multivariate Polynomial Ring in x, y over Rational Field graded by
  x -> [1]
  y -> [1] by ideal(x*y)
```

**Comment by fingolfin** [comment] 2023-05-03 10:20
This looks to me to be primarily a bug in the printing code for graded modules: in the REPL, the ring `S` gets assigned the name `S` and subsequently is printed as `S` in certain contexts. Without the name, it instead gets printed as
```
Multivariate Polynomial Ring in x, y, z over Rational Field graded by
  x -> [1 0]
  y -> [0 1]
  z -> [1 1]
```
(which IMHO is not nice either, but I hope we are going to address this with the new printing scheme.

Anyway, the result is that instead of printing this in the REPL:
```
Graded free module S^1([-1 -2]) ...
```
we print the exact same thing, just with `S` replaced by `Multivariate Polynomial Ring ...` so we see:
```
Graded free module Multivariate Polynomial Ring in x, y, z over Rational Field graded by
  x -> [1 0]
  y -> [0 1]
  z -> [1 1]^1([-1 -2]) ...
```

While one solution would be to ensure that the ring `S` also gets the name `S` in the doctest (I thought we had a mechanism for this now?), I think this is painting over the deeper issue: the printing code for graded free modules *requires* the ring to have name, otherwise the output is unreadable. 

One way to deal with this would be to just make up a nameand/or use a placeholder name like `<unnamed ring>` or so. Then we would print:
```
Graded free module <unnamed ring>^1([-1 -2]) + <unnamed ring>^1([1 -3]) of rank 2 over <unnamed ring>
```
That's not great but at least somewhat useful.

**Comment by fieker** [comment] 2023-05-03 10:26
On Wed, May 03, 2023 at 03:20:48AM -0700, Max Horn wrote:
> This looks to me to be primarily a bug in the printing code for graded modules: in the REPL, the ring `S` gets assigned the name `S` and subsequently is printed as `S` in certain contexts. Without the name, it instead gets printed as
> ```
> Multivariate Polynomial Ring in x, y, z over Rational Field graded by
>   x -> [1 0]
>   y -> [0 1]
>   z -> [1 1]
> ```
> (which IMHO is not nice either, but I hope we are going to address this with the new printing scheme.
> 
> Anyway, the result is that instead of printing this in the REPL:
> ```
> Graded free module S^1([-1 -2]) ...
> ```
> we print the exact same thing, just with `S` replaced by `Multivariate Polynomial Ring ...` so we see:
> ```
> Graded free module Multivariate Polynomial Ring in x, y, z over Rational Field graded by
>   x -> [1 0]
>   y -> [0 1]
>   z -> [1 1]^1([-1 -2]) ...
> ```
> 
> While one solution would be to ensure that the ring `S` also gets the
> name `S` in the doctest (I thought we had a mechanism for this now?),
This is the core of the complaint. It does not seem to work as intended,
so I am looking into it.
> I think this is painting over the deeper issue: the printing code for
> graded free modules *requires* the ring to have name, otherwise the
> output is unreadable. 
This is a seperate issue - albeit an important one

**Comment by wdecker** [comment] 2023-05-03 10:49
Thx! How about merging  the current PR ? We will then improve the printing.

Von meinem iPhone gesendet

**Comment by fieker** [comment] 2023-06-07 09:50
the named printing should have been fixed in Hecke/AA

**Closed as completed by fieker** 2023-06-07 09:50 UTC
Labels: enhancement
