### ISSUE TITLE
Kroki

### ISSUE THREAD

**Issue by fieker** [oscar-system/Oscar.jl#529] opened 2021-07-06 12:02 UTC
Dear Gurus
Wolfram just ran into problems building the documentation: we accidentally unplugged the laptop and thus couldn't build the docu (without errors).
Problem: Kroki requires an active internet connection.
Is this deliberate? A price we're willing to pay? Well known?

From my point of view, this is not a good idea, there should be an offline version or a statically included graphic (tha can be updated every now and then)

**Comment by fingolfin** [comment] 2021-07-06 12:04
It needs an active internet connection?? WHY??? That sounds really bad to me.

**Comment by fieker** [comment] 2021-07-06 12:12
the rendering is done via kroki.io, Wolframs error was DNS error, kroki.io couldn't resolve...

**Comment by wdecker** [comment] 2021-07-06 12:24
ERROR: DNSError: kroki.io, unknown node or service (EAI_NONAME)
Stacktrace:
 [1] render(::Kroki.Diagram, ::String) at /Users/decker/.julia/packages/Kroki/HWTax/src/Kroki.jl:162
 [2] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Kroki.Diagram) at /Users/decker/.julia/packages/Kroki/HWTax/src/Kroki.jl:228
 [3] show at ./multimedia.jl:47 [inlined]
 [4] limitstringmime at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Utilities.jl:616 [inlined]
 [5] display_dict(::Kroki.Diagram) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Utilities.jl:623
 [6] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [7] invokelatest at ./essentials.jl:709 [inlined]
 [8] runner(::Type{Documenter.Expanders.ExampleBlocks}, ::Markdown.Code, ::Documenter.Documents.Page, ::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Expanders.jl:582
 [9] dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::Markdown.Code, ::Vararg{Any,N} where N) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Selectors.jl:170
 [10] expand(::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Expanders.jl:42
 [11] runner(::Type{Documenter.Builder.ExpandTemplates}, ::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Builder.jl:227
 [12] dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Selectors.jl:170
 [13] #2 at /Users/decker/.julia/packages/Documenter/4JDQo/src/Documenter.jl:257 [inlined]
 [14] cd(::Documenter.var"#2#3"{Documenter.Documents.Document}, ::String) at ./file.jl:104
 [15] #makedocs#1 at /Users/decker/.julia/packages/Documenter/4JDQo/src/Documenter.jl:256 [inlined]
 [16] (::Main.BuildDoc.var"#1#2"{Bool,Bool,Array{Any,1}})() at /Users/decker/.julia/dev/Oscar/docs/make_work.jl:201
 [17] cd(::Main.BuildDoc.var"#1#2"{Bool,Bool,Array{Any,1}}, ::String) at ./file.jl:104
 [18] doit(::Bool, ::Bool) at /Users/decker/.julia/dev/Oscar/docs/make_work.jl:196
 [19] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [20] invokelatest at ./essentials.jl:709 [inlined]
 [21] (::Oscar.var"#5#6")() at /Users/decker/.julia/dev/Oscar/src/Oscar.jl:136
 [22] activate(::Oscar.var"#5#6", ::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:964
 [23] build_doc() at /Users/decker/.julia/dev/Oscar/src/Oscar.jl:135
 [24] top-level scope at REPL[2]:1
caused by [exception 1]
DNSError: kroki.io, unknown node or service (EAI_NONAME)
Stacktrace:
 [1] getalladdrinfo(::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Sockets/src/addrinfo.jl:112
 [2] getalladdrinfo at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Sockets/src/addrinfo.jl:121 [inlined]
 [3] getconnection(::Type{Sockets.TCPSocket}, ::SubString{String}, ::String; keepalive::Bool, connect_timeout::Int64, kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol,Symbol},NamedTuple{(:require_ssl_verification, :iofunction, :reached_redirect_limit),Tuple{Bool,Nothing,Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:630
 [4] #getconnection#29 at /Users/decker/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:682 [inlined]
 [5] newconnection(::HTTP.ConnectionPool.Pod, ::Type{T} where T, ::SubString{String}, ::SubString{String}, ::Int64, ::Bool, ::Int64; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit),Tuple{Nothing,Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:597
 [6] getconnection(::Type{HTTP.ConnectionPool.Transaction{MbedTLS.SSLContext}}, ::SubString{String}, ::SubString{String}; connection_limit::Int64, pipeline_limit::Int64, idle_timeout::Int64, reuse_limit::Int64, require_ssl_verification::Bool, kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit),Tuple{Nothing,Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/ConnectionPool.jl:541
 [7] request(::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::Array{UInt8,1}; proxy::Nothing, socket_type::Type{T} where T, reuse_limit::Int64, kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit),Tuple{Nothing,Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/ConnectionRequest.jl:73
 [8] request(::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}, ::HTTP.URIs.URI, ::Vararg{Any,N} where N; kw::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit),Tuple{Nothing,Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/ExceptionRequest.jl:19
 [9] (::Base.var"#56#58"{Base.var"#56#57#59"{ExponentialBackOff,HTTP.RetryRequest.var"#2#3"{Bool,HTTP.Messages.Request},typeof(HTTP.request)}})(::Type{T} where T, ::Vararg{Any,N} where N; kwargs::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :reached_redirect_limit),Tuple{Nothing,Bool}}}) at ./error.jl:301
 [10] #request#1 at /Users/decker/.julia/packages/HTTP/IAI92/src/RetryRequest.jl:44 [inlined]
 [11] request(::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; http_version::VersionNumber, target::String, parent::Nothing, iofunction::Nothing, kw::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:reached_redirect_limit,),Tuple{Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/MessageRequest.jl:51
 [12] request(::Type{HTTP.BasicAuthRequest.BasicAuthLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; kw::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:reached_redirect_limit,),Tuple{Bool}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/BasicAuthRequest.jl:28
 [13] request(::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.BasicAuthRequest.BasicAuthLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; redirect_limit::Int64, forwardheaders::Bool, kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/RedirectRequest.jl:24
 [14] request(::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.BasicAuthRequest.BasicAuthLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer{Union{}}}}}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}) at /Users/decker/.julia/packages/HTTP/IAI92/src/RedirectRequest.jl:21
 [15] request(::String, ::String, ::Array{Pair{SubString{String},SubString{String}},1}, ::Array{UInt8,1}; headers::Array{Pair{SubString{String},SubString{String}},1}, body::Array{UInt8,1}, query::Nothing, kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/decker/.julia/packages/HTTP/IAI92/src/HTTP.jl:314
 [16] request at /Users/decker/.julia/packages/HTTP/IAI92/src/HTTP.jl:314 [inlined] (repeats 2 times)
 [17] render(::Kroki.Diagram, ::String) at /Users/decker/.julia/packages/Kroki/HWTax/src/Kroki.jl:146
 [18] show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Kroki.Diagram) at /Users/decker/.julia/packages/Kroki/HWTax/src/Kroki.jl:228
 [19] show at ./multimedia.jl:47 [inlined]
 [20] limitstringmime at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Utilities.jl:616 [inlined]
 [21] display_dict(::Kroki.Diagram) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Utilities.jl:623
 [22] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [23] invokelatest at ./essentials.jl:709 [inlined]
 [24] runner(::Type{Documenter.Expanders.ExampleBlocks}, ::Markdown.Code, ::Documenter.Documents.Page, ::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Expanders.jl:582
 [25] dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::Markdown.Code, ::Vararg{Any,N} where N) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Selectors.jl:170
 [26] expand(::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Expanders.jl:42
 [27] runner(::Type{Documenter.Builder.ExpandTemplates}, ::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Builder.jl:227
 [28] dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /Users/decker/.julia/packages/Documenter/4JDQo/src/Utilities/Selectors.jl:170
 [29] #2 at /Users/decker/.julia/packages/Documenter/4JDQo/src/Documenter.jl:257 [inlined]
 [30] cd(::Documenter.var"#2#3"{Documenter.Documents.Document}, ::String) at ./file.jl:104
 [31] #makedocs#1 at /Users/decker/.julia/packages/Documenter/4JDQo/src/Documenter.jl:256 [inlined]
 [32] (::Main.BuildDoc.var"#1#2"{Bool,Bool,Array{Any,1}})() at /Users/decker/.julia/dev/Oscar/docs/make_work.jl:201
 [33] cd(::Main.BuildDoc.var"#1#2"{Bool,Bool,Array{Any,1}}, ::String) at ./file.jl:104
 [34] doit(::Bool, ::Bool) at /Users/decker/.julia/dev/Oscar/docs/make_work.jl:196
 [35] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [36] invokelatest at ./essentials.jl:709 [inlined]
 [37] (::Oscar.var"#5#6")() at /Users/decker/.julia/dev/Oscar/src/Oscar.jl:136
 [38] activate(::Oscar.var"#5#6", ::String) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:964
 [39] build_doc() at /Users/decker/.julia/dev/Oscar/src/Oscar.jl:135
 [40] top-level scope at REPL[2]:1

**Comment by thofma** [comment] 2021-07-06 14:29
Will be fixed by https://github.com/Nemocas/AbstractAlgebra.jl/pull/924.

**Comment by fieker** [comment] 2021-07-14 18:36
Solved in aa

**Closed as completed** 2021-07-14 18:35 UTC
